name: Documentation issue
description: Report an issue with the documentation.
title: "[DOCUMENTATION] "
labels: [ documentation ]
assignees:
  - Ayfri

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: A clear and concise description of what the issue is.
      placeholder: "The documentation says that '...', but it should say '...'."
    validations:
      required: true

  - type: textarea
    id: extra-info
    attributes:
      label: Extra information
      description: |
        Please provide any additional information that may be helpful in understanding the issue.
        You can also include screenshots or animated GIFs.
      placeholder: "I'm using a more recent version of Minecraft than the one supported by the library."

  - type: checkboxes
    id: duplication-validation
    attributes:
      label: My issue is not duplicated
      description: I have searched the issues of this repository and believe that this is not a duplicate.
      options:
        - label: This is not a duplicate
          required: true
