name: Update proposal
description: Propose to update the project to a new Minecraft version.
title: "[UPDATE] Update project to"
labels: [ update ]
assignees:
  - Ayfri

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this update proposal!

  - type: input
    id: version
    attributes:
      label: Minecraft version
      description: The version of Minecraft you want to update the project to.
      placeholder: 1.20.5-pre1
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: Changes
      description: A list of changes you want to make to the project.
      placeholder: |
        - [ ] Add `component` field to `set_contents` loot function, which can be equal to a value from an enum of some components.
        - [ ] Add `filtered`, `modifiy_contents`, `set_custom_model_data`, `set_item` loot functions.
        - No changes are required.
        ...
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other
      description: Any other information you want to provide.
      placeholder: "This update will be very long to develop because..."
