name: Publish

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3

        with:
          java-version: 17
          distribution: temurin



      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Grant execute permission for Gradle
        run: chmod +x /home/runner/work/Kore/Kore/gradlew

      - name: Gradle (Publish)

        env:
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.GPG_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.GPG_PASSWORD }}"

          NEXUS_USERNAME: "${{ secrets.NEXUS_USERNAME }}"
          NEXUS_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"

        run: /home/runner/work/Kore/Kore/gradlew publish

      - name: Upload artifact (Main JARs)
        uses: actions/upload-artifact@v3

        with:
          name: JARs (Main)
          path: kore/build/libs/*.jar

      - name: Upload artifact (OOP JARs)
        uses: actions/upload-artifact@v3

        with:
          name: JARs (Modules)
          path: oop/*/build/libs/*.jar
